### PR TITLE
tflog+tfsdklog: Prevent slice/map leaks when setting LoggerOpts

### LINKED ISSUE #126: Logger goroutine-safety: `fatal error: concurrent map writes`
### terraform-plugin-log version

```console
% go list -m github.com/hashicorp/terraform-plugin-log/...
github.com/hashicorp/terraform-plugin-log v0.7.0
```

Relates https://github.com/hashicorp/terraform-provider-aws/issues/29236.

With **v4.53.0**, released 02/02/2023, the Terraform AWS Provider has started to use `terraform-plugin-log` (via [`aws-sdk-go-base`](https://github.com/hashicorp/aws-sdk-go-base)) to log AWS SDK for Go requests and responses.
Under heavy usage we are seeing crashes:

```
fatal error: concurrent map writes
goroutine 1730 [running]:
github.com/hashicorp/terraform-plugin-log/tflog.SetField.func1(...)
	github.com/hashicorp/terraform-plugin-log@v0.7.0/internal/logging/options.go:212
github.com/hashicorp/terraform-plugin-log/tflog.SetField({0xe25bd00, 0xc001d5f890}, {0xce4900e, 0xb}, {0xa619820?, 0xc00089eb90})
	github.com/hashicorp/terraform-plugin-log@v0.7.0/tflog/provider.go:18 +0x111
github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.setAWSFields({0xe25bd00?, 0xc003bc12f0?}, 0xc005cbaa00)
	github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:40 +0x9c
github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.logRequest(0xc005cbaa00)
	github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:69 +0x5f
...
```

https://github.com/hashicorp/terraform-plugin-log/blob/2a7a4a85e924b5cefe5189bd515220a207d90e30/internal/logging/options.go#L205-L215
https://github.com/hashicorp/terraform-plugin-log/blob/2a7a4a85e924b5cefe5189bd515220a207d90e30/tflog/provider.go#L15-L21
https://github.com/hashicorp/aws-sdk-go-base/blob/f0b32e1671652e7f19ebd715676fceb7c37190f2/v2/awsv1shim/logger.go#L38-L51

It is not clear which component is responsible for ensuring goroutine-safety here.

### LINKED ISSUE #131: Fields set with `SetField` leak
### terraform-plugin-log version

```
v0.7.0 (commit 3ca5214047ab31ddc04b997942a52e35dbc31640)
```

### Relevant provider source code

```go
func TestSetFieldSequential(t *testing.T) {
	t.Parallel()

	var outputBuffer bytes.Buffer

	key1 := "key1"
	value1 := "value1"

	key2 := "key2"
	value2 := "value2"

	expectedOutputOriginalLogger := []map[string]interface{}{
		{
			"@level":   "trace",
			"@message": "original logger",
			"@module":  "provider",
			"key1":     "value1",
		},
	}

	expectedOutputNewLogger := []map[string]interface{}{
		{
			"@level":   "trace",
			"@message": "new logger",
			"@module":  "provider",
			"key1":     "value1",
			"key2":     "value2",
		},
	}

	originalCtx := context.Background()
	originalCtx = loggertest.ProviderRoot(originalCtx, &outputBuffer)
	originalCtx = tflog.SetField(originalCtx, key1, value1)

	newCtx := tflog.SetField(originalCtx, key2, value2)

	tflog.Trace(newCtx, "new logger")

	got, err := loggertest.MultilineJSONDecode(&outputBuffer)

	if err != nil {
		t.Fatalf("unable to read multiple line JSON: %s", err)
	}

	if diff := cmp.Diff(expectedOutputNewLogger, got); diff != "" {
		t.Errorf("unexpected output difference: %s", diff)
	}

	tflog.Trace(originalCtx, "original logger")

	got, err = loggertest.MultilineJSONDecode(&outputBuffer)

	if err != nil {
		t.Fatalf("unable to read multiple line JSON: %s", err)
	}

	if diff := cmp.Diff(expectedOutputOriginalLogger, got); diff != "" {
		t.Errorf("unexpected output difference: %s", diff)
	}
}
```

### Expected Behavior

The log entry generated by calling `tflog.Trace(originalCtx, "original logger")` should only have the field `key1` set and not have the field set `key2` set.

### Actual Behavior

Both `key1` and `key2` are set when calling `tflog.Trace(originalCtx, "original logger")`

```
--- FAIL: TestSetFieldSequential (0.00s)
    provider_test.go:158: unexpected output difference:   []map[string]any{
          	{
          		... // 2 identical entries
          		"@module": string("provider"),
          		"key1":    string("value1"),
        + 		"key2":    string("value2"),
          	},
          }
```

### Steps to Reproduce

1. Run the included test `TestSetFieldSequential`

### References

This may be related to #126, since the field map is being modified in-place.

### PR DESCRIPTION
**Pull request by bflad**
Reference #126
Closes #131

Since the `LoggerOpts` struct contains slice and map fields, it is important to ensure any modifications occur on copies of those slices and maps, otherwise the memory reference can wind up being shared. Consumers should always be able to create a new `context.Context` without worrying about shared data.

This change introduces a `Copy()` method for `LoggerOpts` and implements it for option modifier functions which adjust a map or slice.

### CODE REVIEW

**Review by austinvalle — APPROVED** [review]
LGTM 👍🏻

File: tflog/provider_test.go [hunk 1]
```diff
@@ -1199,6 +1488,57 @@ func TestMaskMessageRegexes(t *testing.T) {
...
+
+	originalCtx := context.Background()
+	originalCtx = loggertest.ProviderRoot(originalCtx, &outputBuffer)
+	originalCtx = tflog.MaskMessageRegexes(originalCtx, regexp.MustCompile("original"))
+
+	newCtx := tflog.MaskMessageRegexes(originalCtx, regexp.MustCompile("new"))
+
+	tflog.Trace(originalCtx, "original should be masked")
+	tflog.Trace(originalCtx, "new should be preserved")
+	tflog.Trace(newCtx, "new should be masked")
```
Comment (bendbennett) [inline tflog/provider_test.go:1505]: Is it worth using different log levels for `originalCtx` and `newCtx` in order to be able to differentiate between them in the `expectedOutput`?

File: tflog/provider_test.go [hunk 2]
```diff
@@ -1293,6 +1633,57 @@ func TestMaskMessageStrings(t *testing.T) {
...
+
+	originalCtx := context.Background()
+	originalCtx = loggertest.ProviderRoot(originalCtx, &outputBuffer)
+	originalCtx = tflog.MaskMessageStrings(originalCtx, "original")
+
+	newCtx := tflog.MaskMessageStrings(originalCtx, "new")
+
+	tflog.Trace(originalCtx, "original should be masked")
+	tflog.Trace(originalCtx, "new should be preserved")
+	tflog.Trace(newCtx, "new should be masked")
```
Comment (bendbennett) [inline tflog/provider_test.go:1650]: Is it worth using different log levels for `originalCtx` and `newCtx` in order to be able to differentiate between them in the `expectedOutput`?

**Review by bendbennett — APPROVED** [review]
LGTM 👍

File: tflog/provider_test.go (hunk 1 above)
Comment (bflad) [reply tflog/provider_test.go:1505]: Sure thing -- will adjust
